/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Game.java
 *
 * Created on Oct 23, 2011, 4:42:00 PM
 */
package Client;

import javax.swing.*;

/**
 *
 * @author quanmt
 */
public class Game extends javax.swing.JFrame {

    private int totalBox = 9;
    private int playerState;
    private int opponentState;
    Box[] boxes;
    
    boolean lock = true;
    
    Client client;
    
    /** Creates new form Game */
    public Game() {
        super("Quan MT - TicTacToe");
        initComponents();
        this.initBoxes();
    }
    
    // game play
    void play () {
        while (true) {
            String[] parts = this.client.read();
            
            if (this.processMessage(parts[0], parts[1])) {
                break;
            }
        }
        
        this.client.close();
    }
    
    /** Messages receiving
     * playerState|1 - set state
     * opponentChose|7 - opponent chose box 7
     * unlock|1 - unlock
     * result|win - result win
     * result|lose - result lose
     */
    boolean processMessage (String type, String data) {
        // set player sate
        if (type.equals("playerState")) {
            this.playerState = Integer.valueOf(data);
            if (this.playerState == Box.StateCircle) {
                this.opponentState = Box.StateCross;
            } else {
                this.opponentState = Box.StateCircle;
            }
            this.displayPlayerState();
        } else if (type.equals("unlock")) {
            this.lock = false;
            this.message.setText("Đến lượt bạn!");
        } else if (type.equals("opponentChose")) {
            int index = Integer.valueOf(data);
            this.boxes[index].changeState(this.opponentState);
            this.lock = false;
            this.message.setText("Đến lượt bạn!");
        } else if (type.equals("result")) {
            this.lock = true;
            String result;
            if (data.equals("win")) {
                result = "Thắng";
            } else {
                result = "Thua";
            }
            this.message.setText(result);
            return true;
        }
        
        return false;
    }
    
    void start () {
        this.client = new Client("localhost", 19999, this);
        this.client.start();
    }
    
    void initBoxes () {
        boxes = new Box[9];
        boxes[0] = new Box(this.box0);
        boxes[1] = new Box(this.box1);
        boxes[2] = new Box(this.box2);
        boxes[3] = new Box(this.box3);
        boxes[4] = new Box(this.box4);
        boxes[5] = new Box(this.box5);
        boxes[6] = new Box(this.box6);
        boxes[7] = new Box(this.box7);
        boxes[8] = new Box(this.box8);
    }
    
    void displayPlayerState () {
        if (this.playerState == Box.StateCircle) {
            this.playerStateLabel.setText("O");
        } else {
            this.playerStateLabel.setText("X");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box0 = new javax.swing.JButton();
        box1 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();
        box4 = new javax.swing.JButton();
        box5 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        playerStateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        box0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box0ActionPerformed(evt);
            }
        });

        box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/blank.gif"))); // NOI18N
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        message.setText(" ");

        playerStateLabel.setText(" ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(message, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(31, 31, 31)
                        .add(playerStateLabel))
                    .add(layout.createSequentialGroup()
                        .add(box0)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box2))
                    .add(layout.createSequentialGroup()
                        .add(box3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box5))
                    .add(layout.createSequentialGroup()
                        .add(box6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(box8)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(box2)
                    .add(box1)
                    .add(box0))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(box4)
                        .add(box3))
                    .add(box5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, box6)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, box8)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, box7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(message)
                    .add(playerStateLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box0ActionPerformed
        this.chose(0);
    }//GEN-LAST:event_box0ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        this.chose(1);
    }//GEN-LAST:event_box1ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        this.chose(2);
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        this.chose(3);
    }//GEN-LAST:event_box3ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        this.chose(4);
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        this.chose(5);
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        this.chose(6);
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        this.chose(7);
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        this.chose(8);
    }//GEN-LAST:event_box8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Game game = new Game();
        game.setVisible(true);
        game.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box0;
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JLabel message;
    private javax.swing.JLabel playerStateLabel;
    // End of variables declaration//GEN-END:variables

    private void chose(int i) {
        if (lock != true && this.boxes[i].getState() == Box.StateBlank) {
            this.boxes[i].changeState(this.playerState);
            this.lock = true;
            this.message.setText("Đợi đối thủ đánh");
            this.client.send("chose", String.valueOf(i));
        }
    }
}
